PROGRAM TEST;

VAR
  MFILEPATH: STRING;
BEGIN
  WRITELN(PROMPT);
  READLN(MFILEPATH);
  IF MFILEPATH = '' THEN
  BEGIN
    MFILEPATH := STRPAS(DEFAULTFILEPATH);
  END;
  { MFILEPATH := '../../test/' + MFILEPATH; }
  RESULT := READTEXTFILETOSTRING(MFILEPATH);
END.